### ISSUE TITLE
About Carter constant

### ISSUE THREAD

**Issue by SenYang-Physics** [kul-arun/orbital-evolution-of-extreme-mass-ratio-inspirals#2]
This project is very inspiring. But I don't know why the Carter constant does not appear.

**Comment by kul-arun** [comment]
The existence of such a constant will depend on the spacetime properties.

If the spacetime is stationary and axisymmetric, we have 2 symmetries.
These along with the conservation of the rest mass of the test particle
gives a total of 3 symmetries. The existence of the additional Carter
symmetry ensures that the equations of motion in the Kerr spacetime is
Louville integrable. But we can break this symmetry by introducing certain
terms into the components of the metric tensor, and this leads to the
vanishing of the Carter constant. See the paper linked in the project
description about a modified Johannsen metric.
